# Generated by Django 4.0.2 on 2022-02-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_alter_news_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
